### ISSUE TITLE
Non-ASCII character seen before =encoding

### ISSUE THREAD

**Issue by andk** [jwieland/embedly-perl#3]
Sample fail report:

http://www.cpantesters.org/cpan/report/974c991c-a582-11e2-85f0-f94937c54803

Recent Pod::Simple and Test::Pod are required to reproduce.

It's getting more important now that perl 5.18 is about to be released and Pod::Simple will become more widespread.

HTH && Thanks,

**Comment by jwieland** [comment]
Thanks,  I've been wondering about that error.  Its not obvious looking through the POD documentation in the lib.  It says the error is on line 117, but I see nothing wrong.  

https://github.com/jwieland/embedly-perl/blob/master/lib/WebService/Embedly.pm#L117

I will look a little harder later today.  But if you can see where the error is let me know

**Comment by andk** [comment]
Jason Wieland notifications@github.com writes:

> I will look a little harder later today. But if you can see where the error is
> let me know

Line 117 as hex dump:

0007200 0a 54 68 65 20 72 65 73 70 6f 6e 73 65 20 66 6f  >.The response fo<
0007220 72 6d 61 74 20 e2 80 93 20 41 63 63 65 70 74 65  >rmat ... Accepte<
0007240 64 20 76 61 6c 75 65 73 3a 20 28 78 6d 6c 2c 20  >d values: (xml, <

e2 80 93 is an EN DASH

## 

andreas

**Comment by jwieland** [comment]
– vs. - interesting, sloopy cut and paste?  Thanks..  Also.. with the bad char it still passes podchecker and podlint

[jason@jwiedev embedly-perl]$ podlint lib/WebService/Embedly.pm

[jason@jwiedev embedly-perl]$ podchecker lib/WebService/Embedly.pm 
**\* WARNING: empty section in previous paragraph at line 306 in file lib/WebService/Embedly.pm
**\* WARNING: empty section in previous paragraph at line 308 in file lib/WebService/Embedly.pm
**\* WARNING: empty section in previous paragraph at line 514 in file lib/WebService/Embedly.pm
lib/WebService/Embedly.pm pod syntax OK.

And it passes the POD tests

t/00-load.t ......... 1/? # Testing WebService::Embedly  0.09, Perl 5.014004, /usr/bin/perl
t/00-load.t ......... ok  
t/01-basic-usage.t .. ok  
t/02-complete-oo.t .. ok  
t/manifest.t ........ skipped: Author tests not required for installation
t/pod-coverage.t .... ok  
t/pod.t ............. ok 

Must be a legal utf8 char on linux?

I've updated the code and released.  
Thank you

**Comment by andk** [comment]
Jason Wieland notifications@github.com writes:

> – vs. - interesting, sloopy cut and paste? Thanks.. Also.. with the bad char it
> still passes podchecker and podlint
> [...]
> And it passes the POD tests
> [...]
> Must be a legal utf8 char on linux?

Sorry, I don't know the full story of all supporting tools around POD.
All I know is that I saw fail reports, I sent you a link to a fail
report, and that all this only happens with recent Pod::Simple.

> I've updated the code and released.
> Thank you

Thanks to you! (But note that I do not yet see it on CPAN)

## 

andreas

**Comment by jwieland** [comment]
Yep, new cpan release on the way
